### ISSUE TITLE
Typo in window title

### ISSUE THREAD

**Issue by cvigilv** [rockyzhang24/dotfiles#1]
Hi! Was skimming through your neovim config and noticed a typo you may like to fix. 

Great config btw, tons of customized behavior I find interesting.

https://github.com/rockyzhang24/dotfiles/blob/b38da41b944a47aacd2833a316d63f172505781a/.config/nvim/lua/rockyz/tabline.lua#L30C25-L30C25

**Comment by rockyzhang24** [comment]
Thank you so much. I will correct it right now. Glad you like my config and find something useful :)
